[build]
builder = "NIXPACKS"

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn ali_backend.wsgi --chdir ali_backend --workers 3 --timeout 120 --bind 0.0.0.0:$PORT"
